"""Trusted game, batch, and arena orchestration."""

from .arena import (
    ArenaConfig,
    ArenaReport,
    PairedBootstrapInterval,
    PairedSeedOutcome,
    SeatStats,
    paired_bootstrap_interval,
    run_arena,
    schedule_arena,
    wilson_interval,
)
from .batch import iter_games
from .corpus import corpus_declaration, run_resumable_corpus
from .game import (
    AdvanceResult,
    AgentController,
    AgentSpec,
    GameSession,
    GameSpec,
    HumanController,
    InvalidAgentActionError,
    advance_until_human_or_terminal,
    create_agent_session,
    decision_actor,
    run_game,
    step_agent,
    submit_human_action,
)
from .iteration import (
    IterationConfig,
    IterationError,
    IterationPlan,
    IterationResult,
    resolve_iteration_plan,
    run_iteration,
)
from .promotion import (
    AttemptAssessment,
    BootstrapMeanInterval,
    PlateauDecision,
    PromotionDecision,
    PromotionEvidence,
    PromotionPolicy,
    assess_attempt,
    bootstrap_mean_interval,
    detect_plateau,
    evaluate_promotion,
)
from .self_play import (
    GENERATION_EPSILONS,
    GenerationConfig,
    generation_config_from_agent,
    learned_self_play_agent,
    planned_epsilon,
    schedule_generation,
)

__all__ = [
    "GENERATION_EPSILONS",
    "AdvanceResult",
    "AgentController",
    "AgentSpec",
    "ArenaConfig",
    "ArenaReport",
    "AttemptAssessment",
    "BootstrapMeanInterval",
    "GameSession",
    "GameSpec",
    "GenerationConfig",
    "HumanController",
    "InvalidAgentActionError",
    "IterationConfig",
    "IterationError",
    "IterationPlan",
    "IterationResult",
    "PairedBootstrapInterval",
    "PairedSeedOutcome",
    "PlateauDecision",
    "PromotionDecision",
    "PromotionEvidence",
    "PromotionPolicy",
    "SeatStats",
    "advance_until_human_or_terminal",
    "assess_attempt",
    "bootstrap_mean_interval",
    "corpus_declaration",
    "create_agent_session",
    "decision_actor",
    "detect_plateau",
    "evaluate_promotion",
    "generation_config_from_agent",
    "iter_games",
    "learned_self_play_agent",
    "paired_bootstrap_interval",
    "planned_epsilon",
    "resolve_iteration_plan",
    "run_arena",
    "run_game",
    "run_iteration",
    "run_resumable_corpus",
    "schedule_arena",
    "schedule_generation",
    "step_agent",
    "submit_human_action",
    "wilson_interval",
]
