"""Optional NumPy/PyTorch learning components.

This package is intentionally not imported from the core package or existing agent registry.
Install the ``rl`` extra before importing it.
"""

from .checkpoint import (
    CheckpointCompatibility,
    CheckpointCompatibilityError,
    CheckpointError,
    CheckpointIntegrityError,
    LoadedCheckpoint,
    SavedCheckpoint,
    inspect_checkpoint,
    load_checkpoint,
    save_checkpoint,
    tensor_digest,
)
from .dataset import (
    DATASET_SCHEMA_VERSION,
    DatasetError,
    DatasetSplit,
    MaterializedDataset,
    TrainingSample,
    extract_game_samples,
    load_dataset,
    materialize_dataset,
    save_dataset,
)
from .evaluation import (
    GamePredictionMetrics,
    RecordEvaluation,
    RecordEvaluationError,
    evaluate_records,
)
from .model import CandidateMLP, CandidateValueModel, create_model, model_spec
from .ranking import (
    RANKING_DATASET_VERSION,
    RANKING_LOSS_VERSION,
    RankingDataset,
    RankingError,
    RankingMetrics,
    RankingSplit,
    RankingTrainingConfig,
    RankingTrainingResult,
    load_ranking_dataset,
    materialize_ranking_dataset,
    save_ranking_dataset,
    train_ranking_model,
)
from .structured_checkpoint import (
    LoadedStructuredCheckpoint,
    SavedStructuredCheckpoint,
    StructuredCheckpointCompatibility,
    StructuredCheckpointCompatibilityError,
    StructuredCheckpointError,
    StructuredCheckpointInspection,
    StructuredCheckpointIntegrityError,
    inspect_structured_checkpoint,
    load_structured_checkpoint,
    save_structured_checkpoint,
    structured_tensor_digest,
)
from .structured_dataset import (
    STRUCTURED_DATASET_SCHEMA_VERSION,
    StructuredDatasetError,
    StructuredDatasetSplit,
    StructuredMaterializedDataset,
    StructuredTrainingSample,
    extract_structured_game_samples,
    load_structured_dataset,
    load_verified_step2_corpus,
    materialize_structured_dataset,
    save_structured_dataset,
)
from .structured_model import StructuredResidualMLP, create_structured_model
from .structured_train import (
    StructuredTrainingConfig,
    StructuredTrainingData,
    StructuredTrainingError,
    StructuredTrainingResult,
    evaluate_structured_model,
    train_structured_model,
)
from .train import TrainingConfig, TrainingData, TrainingResult, evaluate_model, train_model

__all__ = [
    "DATASET_SCHEMA_VERSION",
    "RANKING_DATASET_VERSION",
    "RANKING_LOSS_VERSION",
    "STRUCTURED_DATASET_SCHEMA_VERSION",
    "CandidateMLP",
    "CandidateValueModel",
    "CheckpointCompatibility",
    "CheckpointCompatibilityError",
    "CheckpointError",
    "CheckpointIntegrityError",
    "DatasetError",
    "DatasetSplit",
    "GamePredictionMetrics",
    "LoadedCheckpoint",
    "LoadedStructuredCheckpoint",
    "MaterializedDataset",
    "RankingDataset",
    "RankingError",
    "RankingMetrics",
    "RankingSplit",
    "RankingTrainingConfig",
    "RankingTrainingResult",
    "RecordEvaluation",
    "RecordEvaluationError",
    "SavedCheckpoint",
    "SavedStructuredCheckpoint",
    "StructuredCheckpointCompatibility",
    "StructuredCheckpointCompatibilityError",
    "StructuredCheckpointError",
    "StructuredCheckpointInspection",
    "StructuredCheckpointIntegrityError",
    "StructuredDatasetError",
    "StructuredDatasetSplit",
    "StructuredMaterializedDataset",
    "StructuredResidualMLP",
    "StructuredTrainingConfig",
    "StructuredTrainingData",
    "StructuredTrainingError",
    "StructuredTrainingResult",
    "StructuredTrainingSample",
    "TrainingConfig",
    "TrainingData",
    "TrainingResult",
    "TrainingSample",
    "create_model",
    "create_structured_model",
    "evaluate_model",
    "evaluate_records",
    "evaluate_structured_model",
    "extract_game_samples",
    "extract_structured_game_samples",
    "inspect_checkpoint",
    "inspect_structured_checkpoint",
    "load_checkpoint",
    "load_dataset",
    "load_ranking_dataset",
    "load_structured_checkpoint",
    "load_structured_dataset",
    "load_verified_step2_corpus",
    "materialize_dataset",
    "materialize_ranking_dataset",
    "materialize_structured_dataset",
    "model_spec",
    "save_checkpoint",
    "save_dataset",
    "save_ranking_dataset",
    "save_structured_checkpoint",
    "save_structured_dataset",
    "structured_tensor_digest",
    "tensor_digest",
    "train_model",
    "train_ranking_model",
    "train_structured_model",
]
